name: Release Plazmaclip

on:
  push:
  workflow_dispatch:

jobs:
  release:
    name: Release Plazmaclip
    strategy:
      matrix:
        base_jdk: [21]
        os: [ubuntu-22.04]

    if: "!startsWith(github.event.commits[0].message, '[CI-Skip]')"
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up GraalVM ${{ matrix.base_jdk }}
        uses: graalvm/setup-graalvm@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          java-version: ${{ matrix.base_jdk }}
          version: latest
          cache: 'gradle'

      - name: Publish Packages
        if: ${{ github.ref_name == 'master' }}
        env:
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
          SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
          SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
          SIGN_KEYSTORE_DATA: ${{ secrets.SIGN_KEYSTORE_DATA }}
          SIGN_KEYSTORE_PASSWORD: ${{ secrets.SIGN_KEYSTORE_PASSWORD }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          ./gradlew publish --info --stacktrace
